# Generated by Django 5.0.1 on 2024-01-14 21:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название мероприятия')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание мероприятия')),
                ('image', models.ImageField(upload_to='ivents_images', verbose_name='Афиша мероприятия')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата проведения мероприятия')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='Название организации')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание организации')),
                ('address', models.CharField(max_length=128, verbose_name='Адрес организации')),
                ('postcode', models.CharField(max_length=6, verbose_name='Почтовый индекс')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Organization_Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.organization')),
            ],
            options={
                'verbose_name': 'Связь организации и мероприятия',
                'verbose_name_plural': 'Cвязи организацией и мероприятий',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='organizations',
            field=models.ManyToManyField(through='events.Organization_Event', to='events.organization', verbose_name='Организовывающие организации'),
        ),
    ]
