# Generated by Django 5.0.1 on 2024-01-15 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_user_events_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Статус персонала сервиса'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.organization', verbose_name='Организация, в которой работает пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Номер телефона'),
        ),
        migrations.CreateModel(
            name='EventOrganizers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Орг. комитет мероприятия',
                'verbose_name_plural': 'Орг. комитеты мероприятий',
            },
        ),
        migrations.CreateModel(
            name='OrganizationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.organization')),
            ],
            options={
                'verbose_name': 'Связь организации и мероприятия',
                'verbose_name_plural': 'Cвязи организацией и мероприятий',
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='organizations',
            field=models.ManyToManyField(through='events.OrganizationEvent', to='events.organization', verbose_name='Организовывающие организации'),
        ),
        migrations.DeleteModel(
            name='Organization_Event',
        ),
    ]
