# Generated by Django 5.0.1 on 2024-01-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_user_first_name_alter_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventorganizers',
            options={'verbose_name': 'Участие пользователя в организации мероприятий', 'verbose_name_plural': 'Участии пользователей в организации мероприятий'},
        ),
        migrations.AddField(
            model_name='user',
            name='events',
            field=models.ManyToManyField(blank=True, through='events.EventOrganizers', to='events.event', verbose_name='Мероприятий, в которых участвует пользователь'),
        ),
    ]
