# Generated by Django 5.0.1 on 2024-01-15 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_eventorganizers_options_user_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventorganizers',
            old_name='event',
            new_name='event_id',
        ),
        migrations.RenameField(
            model_name='eventorganizers',
            old_name='user',
            new_name='user_id',
        ),
    ]
