# Generated by Django 5.0.1 on 2024-01-16 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_rename_event_eventorganizers_event_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventorganizers',
            options={'verbose_name': 'Участие пользователя в организации мероприятий', 'verbose_name_plural': 'Участие пользователей в организации мероприятий'},
        ),
    ]
