# Generated by Django 5.0.1 on 2024-01-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='Название организации')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание организации')),
                ('address', models.CharField(max_length=128, verbose_name='Адрес организации')),
                ('postcode', models.CharField(max_length=6, verbose_name='Почтовый индекс')),
            ],
        ),
    ]
